development:
  adapter: postgresql
  host: localhost
  username: postgres
  password:
  database: mangar_development
  encoding: unicode
  pool: 25

test:
  adapter: postgresql
  host: localhost
  username: postgres
  password:
  database: mangar_test
  encoding: unicode
  pool: 25

production:
  adapter: postgresql
  host: localhost
  username: postgres
  password:
  database: mangar_production
  encoding: unicode
  pool: 25